### ISSUE TITLE
Passing custom data attributes not documented well 

### ISSUE THREAD

**Issue by zackster** [usefomo/fomo-ruby-sdk#2]
README needs examples.  I was able to get a custom attribute passed into the API via curl, but trying the same thing via the SDK resulted in silent failure.  I had to involve the 'httplog' gem just to see an error message.

**Comment by ryanckulp** [comment]
@zackster hey Zack, i'm not sure i follow.

our README has this example:

```ruby
# Add event custom attributes
event.add_custom_event_field('variable_name', 'value')

created_event = client.create_event(event)
```

i've just tested, and this syntax works.

**make a template**

<img width="421" alt="test-template" src="https://user-images.githubusercontent.com/3083888/34014930-e26afd1e-e0ea-11e7-9b5e-321309bb9111.png">

**create a request**

```ruby
require 'fomo'
client = Fomo.new('XXX') # insert your auth token

event = FomoEvent.new

event.event_type_id = YYY # insert an integer ID
event.first_name = 'Ryan'
event.add_custom_event_field('custom', 'an api test')
```

**produces**

<img width="452" alt="test-event-result" src="https://user-images.githubusercontent.com/3083888/34014939-e7c200a0-e0ea-11e7-9e3b-fd20a7970339.png">

**Comment by zackster** [comment]
@ryanckulp good to know... I was using the syntax in the documentation on your website (Ruby) ... https://docs.usefomo.com/reference#create   .. website docs appear out-of-date since neither A nor B are the current paradigms

**Comment by ryanckulp** [comment]
@zackster 10-4, good find!
